// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IFiltersFields {
  /** Name */
  name: string;

  /** Filters List */
  filtersList: string[];
}

export interface IFilters extends Entry<IFiltersFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'filters';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IProjectFields {
  /** Title */
  title: string;

  /** Title Full */
  titleFull?: string | undefined;

  /** Technologies */
  technologies?: string[] | undefined;

  /** Logo */
  logo?: Asset | undefined;

  /** Image */
  image?: Asset | undefined;

  /** Description */
  description?: string | undefined;

  /** Link */
  link?: string | undefined;

  /** Link Text */
  linkText?: string | undefined;

  /** Date End */
  dateEnd?: string | undefined;

  /** Date From */
  dateFrom?: string | undefined;

  /** Content */
  content?: IProjectContentBlock[] | undefined;

  /** Name */
  name: string;
}

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'project';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IProjectContentBlockFields {
  /** Title */
  title: string;

  /** Images */
  images?: Asset[] | undefined;

  /** Text Block 1 */
  textBlock1?: string | undefined;

  /** Text Block 2 */
  textBlock2?: string | undefined;

  /** iFrame */
  iFrame?: string | undefined;
}

export interface IProjectContentBlock
  extends Entry<IProjectContentBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'projectContentBlock';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'filters' | 'project' | 'projectContentBlock';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
